### PR TITLE
Proposition Fixity  _`⊜_ 

### PR DESCRIPTION
**Pull request by Sofia-Insa**
src/Tactic/RingSolver.agda:144,3-7 --- `` _`⊜_`` :
```  		 _`⊜_ : Term → Term → Term
  		 x `⊜ y = quote _⊜_  $ʳ (`numberOfVariables ⟅∷⟆ x ⟨∷⟩ y ⟨∷⟩ [])
```  		 
where  `_⊜_`  is in Tactic.RingSolver.NonReflective
`infixl 6 _⊜_`

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Any particular reason for 6?

**Comment by Sofia-Insa** [comment]
[src/Tactic/RingSolver.agda](https://github.com/agda/agda-stdlib/blob/master/src/Tactic/RingSolver.agda) : 144,3-7 ---  _`⊜_ :

```Agda 
  _`⊜_ : Term → Term → Term
  x `⊜ y = quote _⊜_  $ʳ (`numberOfVariables ⟅∷⟆ x ⟨∷⟩ y ⟨∷⟩ [])
``` 

`` _`⊜_`` calls ` _⊜_ ` that has `infixl 6 _⊜_`

**Comment by JacquesCarette** [comment]
That's probably as good a reason as any.

**Comment by Saransh-cpp** [comment]
Merging this in!

(slowly wrapping up leftover work)

**Pull request merged**
